scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: robot_body_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link # Or your lidar frame
        min_x: -0.5
        max_x: 0.5
        min_y: -0.5
        max_y: 0.5
        min_z: -0.5
        max_z: 0.5
        
